/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmeans;

import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.scene.Scene;
import javafx.scene.chart.BubbleChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.stage.Stage;
 
/**
 *
 * @author Nader
 */

public class Resultat extends javax.swing.JFrame{

    /**
     * Creates new form Resultat
     */
    public Resultat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        charts = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(70, 70));
        getContentPane().setLayout(null);

        res.setEditable(false);
        res.setBackground(new java.awt.Color(51, 0, 204));
        res.setColumns(20);
        res.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        res.setForeground(new java.awt.Color(255, 255, 255));
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 100, 770, 220);

        charts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        charts.setForeground(new java.awt.Color(0, 51, 255));
        charts.setText("Affichage Chart");
        charts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartsMouseClicked(evt);
            }
        });
        charts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsActionPerformed(evt);
            }
        });
        getContentPane().add(charts);
        charts.setBounds(630, 330, 140, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("K-Means");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 0, 770, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Réalisé par : Tounekti Nader / Abdelkader Jouini");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 380, 450, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nader\\Desktop\\Template.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chartsActionPerformed

    private void chartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartsMouseClicked
        // TODO add your handling code here:
        //BubbleChartSample b= new BubbleChartSample()
        //launch();
        String[] ars=null;
        BubbleChartSample.main(ars);
        
    
        //lenna bech n7otou el code
        
    }//GEN-LAST:event_chartsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton charts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextArea res;
    // End of variables declaration//GEN-END:variables
}
